#
#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#
#
#spring:
#  datasource:
##    password: papai120499
##    url: jdbc:postgresql://localhost:5432/testdb
##    username: shuvayan
#    url : jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
#    username : ${POSTGRES_USER}
#    password : ${POSTGRES_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    show-sql: true
#
#  session:
#    store-type: jdbc
#    jdbc:
#      table-name: SPRING_SESSION
#      initialize-schema: always
#
#
#
#
#
#
#
#
#
##  mail:
##    host: localhost
##    port: 1025
##    username: hello
##    password: hello
##
##    properties:
##      mail:
##        smtp:
##          ssl:
##            trust: "*"
##          auth: true
##          starttls:
##            enable: true
##          connectiontimeout: 5000
##          timeout: 3000
##          writetimeout: 5000
